# Generated by Django 4.1.2 on 2022-11-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='state',
            new_name='country',
        ),
    ]
