# Generated by Django 4.1.2 on 2022-11-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_shipping_order_order_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_confirmation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
