# Generated by Django 4.1.2 on 2022-11-11 21:16

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_payment_alter_customer_email_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expiration',
        ),
        migrations.AddField(
            model_name='payment',
            name='cc_code',
            field=creditcards.models.SecurityCodeField(default='366', max_length=4, verbose_name='security code'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cc_expiry',
            field=creditcards.models.CardExpiryField(default='5/22', verbose_name='expiration date'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cc_number',
            field=creditcards.models.CardNumberField(default='1234567891234567', max_length=25, verbose_name='card number'),
        ),
    ]
