# Generated by Django 4.1.2 on 2022-11-11 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_payment_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
