# Generated by Django 4.1.2 on 2022-11-11 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_payment_card_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expiration',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 11, 21, 36, 22, 425530, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
