# Generated by Django 4.1.2 on 2022-11-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_product_size_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Sleeping bag', 'Sleeping bag'), ('Jacket', 'Jacket'), ('Accessory', 'Accessory')], default=('Sleeping bag', 'Sleeping bag'), max_length=30),
        ),
    ]
