# Generated by Django 4.1.2 on 2022-11-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Sleeping bag', 'Sleeping bag'), ('Jacket', 'Jacket'), ('Accessory', 'Accessory')], default=[('Sleeping bag', 'Sleeping bag')], max_length=30),
        ),
    ]
