# Generated by Django 4.1.2 on 2022-11-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_payment_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='card_data',
            new_name='payment',
        ),
    ]
