# Generated by Django 4.1.2 on 2022-11-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_remove_payment_order_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='FirstName',
        ),
        migrations.AddField(
            model_name='customer',
            name='LastName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
