# Generated by Django 4.1.2 on 2022-11-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_customer_firstname_alter_customer_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='LastName',
        ),
    ]
