# Generated by Django 4.1.2 on 2022-11-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_remove_customer_firstname_remove_customer_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='FirstName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='LastName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
