# Generated by Django 4.1.2 on 2022-11-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_customer_firstname_customer_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='LastName',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='hallo', max_length=30),
            preserve_default=False,
        ),
    ]
