# Generated by Django 4.1.2 on 2022-11-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_rename_name_customer_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
